/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TalkIndexImport } from './routes/talk/index'
import { Route as TalkEditIdImport } from './routes/talk/edit.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TalkIndexRoute = TalkIndexImport.update({
  id: '/talk/',
  path: '/talk/',
  getParentRoute: () => rootRoute,
} as any)

const TalkEditIdRoute = TalkEditIdImport.update({
  id: '/talk/edit/$id',
  path: '/talk/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/talk/': {
      id: '/talk/'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkIndexImport
      parentRoute: typeof rootRoute
    }
    '/talk/edit/$id': {
      id: '/talk/edit/$id'
      path: '/talk/edit/$id'
      fullPath: '/talk/edit/$id'
      preLoaderRoute: typeof TalkEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/talk': typeof TalkIndexRoute
  '/talk/edit/$id': typeof TalkEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/talk': typeof TalkIndexRoute
  '/talk/edit/$id': typeof TalkEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/talk/': typeof TalkIndexRoute
  '/talk/edit/$id': typeof TalkEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/talk' | '/talk/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/talk' | '/talk/edit/$id'
  id: '__root__' | '/' | '/talk/' | '/talk/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TalkIndexRoute: typeof TalkIndexRoute
  TalkEditIdRoute: typeof TalkEditIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TalkIndexRoute: TalkIndexRoute,
  TalkEditIdRoute: TalkEditIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/talk/",
        "/talk/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/talk/": {
      "filePath": "talk/index.jsx"
    },
    "/talk/edit/$id": {
      "filePath": "talk/edit.$id.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
